name: Automatically crawl CVEs 
on:
  schedule:
    - cron:  '34 * * * *'


jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt

    # 本项目通过 -ac 参数内置了自动提交变更到 Github 的功能，不需额外再在 workflow 添加 job/step
    - name: Crawl CVEs and deploy to Github Page
      env:
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      run: |-
        python main.py -ac -mp $MAIL_PASSWORD

