name: Automatically crawl CVEs 
on:
  schedule:
    - cron:  '15 * * * *'


jobs:
  init-env:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt

  crawler:
    - name: Crawl CVEs
      run: |-
        python main.py -mg

    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: ${{ secrets.MAIL_SMTP }}
        server_port: 465
        username: ${{secrets.MAIL_USER}}
        password: ${{secrets.MAIL_PASS}}
        subject: 威胁情报播报
        body: file://cache/mail.dat
        to: ${{ secrets.MAIL_RECV }}
        from: ${{secrets.MAIL_USER}}
        content_type: text/html

  deploy:
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content" || exit 0
        git push

